### ISSUE TITLE
Use compiled `fortune-vn` file instead

### ISSUE THREAD

**Issue by icy** [tentamen/fortune-vn-twit#1]
From now we have a pre-compiled file of all quotes here

https://github.com/icy/fortune-vn/blob/master/fortune-vn

This file should be stable and being formatted correctly. Please update the code to use this file instead. 

Thanks a lot @tentamen

**Comment by quan-nh** [comment]
@icy some separated lines `%` are missed between 2 quotes on that file, e.g. https://github.com/icy/fortune-vn/blob/059db2a26d9a2b4112baf5dce8bdac33dcd276d0/fortune-vn#L31

anw, reading from data/*.txt files is fine for me :)

**Comment by icy** [comment]
You're fast :) I have fixed that joining issue. yes you can read from `data/`; just keep in mind that sometimes contributor may add some extra lines at the end.
